# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='gateway',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bhello.proto\x12\x07gateway\"\x17\n\x08sayHello\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1a\n\x0breturnHello\x12\x0b\n\x03msg\x18\x01 \x01(\t2;\n\x05Hello\x12\x32\n\x05Reply\x12\x11.gateway.sayHello\x1a\x14.gateway.returnHello\"\x00\x62\x06proto3')
)




_SAYHELLO = _descriptor.Descriptor(
  name='sayHello',
  full_name='gateway.sayHello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='gateway.sayHello.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=47,
)


_RETURNHELLO = _descriptor.Descriptor(
  name='returnHello',
  full_name='gateway.returnHello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='gateway.returnHello.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['sayHello'] = _SAYHELLO
DESCRIPTOR.message_types_by_name['returnHello'] = _RETURNHELLO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

sayHello = _reflection.GeneratedProtocolMessageType('sayHello', (_message.Message,), dict(
  DESCRIPTOR = _SAYHELLO,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:gateway.sayHello)
  ))
_sym_db.RegisterMessage(sayHello)

returnHello = _reflection.GeneratedProtocolMessageType('returnHello', (_message.Message,), dict(
  DESCRIPTOR = _RETURNHELLO,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:gateway.returnHello)
  ))
_sym_db.RegisterMessage(returnHello)



_HELLO = _descriptor.ServiceDescriptor(
  name='Hello',
  full_name='gateway.Hello',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=77,
  serialized_end=136,
  methods=[
  _descriptor.MethodDescriptor(
    name='Reply',
    full_name='gateway.Hello.Reply',
    index=0,
    containing_service=None,
    input_type=_SAYHELLO,
    output_type=_RETURNHELLO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLO)

DESCRIPTOR.services_by_name['Hello'] = _HELLO

# @@protoc_insertion_point(module_scope)
