# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hello_pb2 as hello__pb2


class HelloStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Reply = channel.unary_unary(
        '/gateway.Hello/Reply',
        request_serializer=hello__pb2.sayHello.SerializeToString,
        response_deserializer=hello__pb2.returnHello.FromString,
        )


class HelloServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Reply(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Reply': grpc.unary_unary_rpc_method_handler(
          servicer.Reply,
          request_deserializer=hello__pb2.sayHello.FromString,
          response_serializer=hello__pb2.returnHello.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gateway.Hello', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
